"""RAG provider: AWS S3 Vectors — serverless vector search for AWS/Floci.

Uses Amazon S3 Vectors (vector buckets + vector indexes) for similarity
search, with embeddings generated by either:

  - Amazon Bedrock Titan Text Embeddings V2 (1024 dims) — real AWS
  - sentence-transformers/all-MiniLM-L6-v2 (384 dims) — Floci/local fallback

The embedding model is selected via RAG_EMBEDDING_PROVIDER env var:
  "bedrock"  → Titan V2 (1024 dims, requires real AWS)
  "local"    → all-MiniLM-L6-v2 (384 dims, works with Floci)

The S3 Vector index dimension must match the embedding model dimension.
Terraform creates the index with the correct dimension via a variable.

Usage:
  from .rag_s3vectors import build_index, retrieve

  # Indexing (one-time, via Lambda or init container)
  build_index(contracts)

  # Retrieval (at runtime)
  chunks = retrieve("late payment penalty", "SUP-001")
"""

import json
import os
from typing import Dict, List

from .chunking import chunk_text

DEFAULT_TOP_K = 5

# Embedding dimensions per provider
EMBED_DIMS = {
    "bedrock": 1024,  # Amazon Titan Text Embeddings V2
    "local": 384,     # sentence-transformers/all-MiniLM-L6-v2
}


def _get_embedding_provider() -> str:
    """Get the embedding provider from env var (default: local)."""
    return os.environ.get("RAG_EMBEDDING_PROVIDER", "local")


def _get_s3vectors_client():
    """Create a boto3 S3 Vectors client.

    Respects AWS_ENDPOINT_URL for Floci/LocalStack compatibility.
    """
    import boto3

    kwargs = {"region_name": os.environ.get("AWS_DEFAULT_REGION", "eu-west-3")}
    # Floci/LocalStack: AWS_ENDPOINT_URL is set by env.floci
    endpoint = os.environ.get("AWS_ENDPOINT_URL")
    if endpoint:
        kwargs["endpoint_url"] = endpoint

    return boto3.client("s3vectors", **kwargs)


def _get_bedrock_client():
    """Create a boto3 Bedrock Runtime client for Titan embeddings."""
    import boto3

    kwargs = {"region_name": os.environ.get("AWS_DEFAULT_REGION", "eu-west-3")}
    endpoint = os.environ.get("AWS_ENDPOINT_URL")
    if endpoint:
        kwargs["endpoint_url"] = endpoint

    return boto3.client("bedrock-runtime", **kwargs)


# --- Embedding functions ---

_embedder = None


def _embed_local(texts: List[str]) -> List[List[float]]:
    """Embed texts using sentence-transformers/all-MiniLM-L6-v2 (384 dims).

    Used for Floci testing and local development where Bedrock is not
    available or returns stub responses.
    """
    global _embedder
    if _embedder is None:
        from sentence_transformers import SentenceTransformer

        _embedder = SentenceTransformer("sentence-transformers/all-MiniLM-L6-v2")

    vectors = _embedder.encode(texts, normalize_embeddings=True, show_progress_bar=False)
    return [v.tolist() for v in vectors]


def _embed_bedrock(texts: List[str]) -> List[List[float]]:
    """Embed texts using Amazon Titan Text Embeddings V2 (1024 dims).

    Calls Bedrock InvokeModel for each text. Titan V2 accepts up to 8K
    input tokens per call.
    """
    client = _get_bedrock_client()
    results = []

    for text in texts:
        response = client.invoke_model(
            modelId="amazon.titan-embed-text-v2:0",
            body=json.dumps({"inputText": text}),
        )
        result = json.loads(response["body"].read())
        results.append(result["embedding"])

    return results


def embed_texts(texts: List[str]) -> List[List[float]]:
    """Embed texts using the configured embedding provider."""
    provider = _get_embedding_provider()
    if provider == "bedrock":
        return _embed_bedrock(texts)
    else:
        return _embed_local(texts)


def embed_query(query: str) -> List[float]:
    """Embed a single query string."""
    return embed_texts([query])[0]


# --- S3 Vectors operations ---

def _get_vector_bucket_name() -> str:
    return os.environ["VECTOR_BUCKET_NAME"]


def _get_index_name() -> str:
    return os.environ.get("VECTOR_INDEX_NAME", "contract-chunks")


def build_index(contracts: Dict[str, str]) -> dict:
    """Index all contract chunks into S3 Vectors.

    Chunks each contract, embeds each chunk, and batches PutVectors calls.
    Metadata includes supplier_id (filterable) and chunk_text (non-filterable,
    used for retrieval).

    Args:
        contracts: {supplier_id: contract_text} for all suppliers.

    Returns:
        Dict with stats: {chunks, vectors, suppliers, dim}
    """
    from .chunking import CHUNK_SIZE, CHUNK_OVERLAP

    client = _get_s3vectors_client()
    bucket = _get_vector_bucket_name()
    index = _get_index_name()
    provider = _get_embedding_provider()
    dim = EMBED_DIMS[provider]

    print(f"  [rag_s3vectors] Indexing with {provider} embeddings (dim={dim})...")

    # Ensure vector bucket + index exist (create if not)
    _ensure_bucket_and_index(client, bucket, index, dim)

    all_vectors = []
    total_chunks = 0

    for supplier_id, text in contracts.items():
        chunks = chunk_text(text)
        # Embed in batches of 100 to avoid memory spikes
        for batch_start in range(0, len(chunks), 100):
            batch = chunks[batch_start : batch_start + 100]
            embeddings = embed_texts(batch)

            for i, (chunk, embedding) in enumerate(zip(batch, embeddings)):
                chunk_idx = batch_start + i
                all_vectors.append(
                    {
                        "key": f"{supplier_id}_chunk_{chunk_idx}",
                        "data": {"float32": embedding},
                        "metadata": {
                            "supplier_id": supplier_id,
                            "chunk_idx": chunk_idx,
                            "chunk_text": chunk,
                        },
                    }
                )
                total_chunks += 1

            # PutVectors in batches of 500 (S3 Vectors limit)
            if len(all_vectors) >= 500:
                client.put_vectors(
                    vectorBucketName=bucket,
                    indexName=index,
                    vectors=all_vectors[:500],
                )
                all_vectors = all_vectors[500:]

    # Flush remaining vectors
    if all_vectors:
        client.put_vectors(
            vectorBucketName=bucket,
            indexName=index,
            vectors=all_vectors,
        )

    stats = {
        "chunks": total_chunks,
        "vectors": total_chunks,
        "suppliers": len(contracts),
        "dim": dim,
    }
    print(
        f"  [rag_s3vectors] Indexed {stats['vectors']} vectors, "
        f"{stats['suppliers']} suppliers, dim={stats['dim']}"
    )
    return stats


def _ensure_bucket_and_index(client, bucket: str, index: str, dim: int):
    """Create vector bucket and index if they don't exist."""
    # Check/create bucket
    try:
        client.get_vector_bucket(vectorBucketName=bucket)
    except Exception:
        client.create_vector_bucket(vectorBucketName=bucket)
        print(f"  [rag_s3vectors] Created vector bucket: {bucket}")

    # Check/create index
    try:
        client.get_index(vectorBucketName=bucket, indexName=index)
    except Exception:
        client.create_index(
            vectorBucketName=bucket,
            indexName=index,
            dimension=dim,
            distanceMetric="cosine",
            dataType="float32",
        )
        print(f"  [rag_s3vectors] Created vector index: {index} (dim={dim})")


def retrieve(
    query: str,
    supplier_id: str,
    top_k: int = DEFAULT_TOP_K,
) -> List[str]:
    """Retrieve relevant contract chunks from S3 Vectors.

    Args:
        query: natural language query.
        supplier_id: filter results to this supplier (metadata filter).
        top_k: number of chunks to return.

    Returns:
        List of chunk text strings, most relevant first.
    """
    client = _get_s3vectors_client()
    bucket = _get_vector_bucket_name()
    index = _get_index_name()

    # Embed the query
    query_vec = embed_query(query)

    # Query S3 Vectors with metadata filter on supplier_id
    response = client.query_vectors(
        vectorBucketName=bucket,
        indexName=index,
        queryVector={"float32": query_vec},
        topK=top_k,
        returnMetadata=True,
        returnDistance=True,
        filter={"supplier_id": {"$eq": supplier_id}},
    )

    # Extract chunk text from metadata
    chunks = []
    for v in response.get("vectors", []):
        meta = v.get("metadata", {})
        text = meta.get("chunk_text", "")
        if text:
            chunks.append(text)

    return chunks
