apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keda
  namespace: argocd
spec:
  project: aipaas
  source:
    repoURL: https://github.com/lionelmarcus10/aipaas.git
    targetRevision: master
    path: apps/keda
  destination:
    server: https://kubernetes.default.svc
    namespace: keda-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
