apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pod-security
  namespace: argocd
  labels:
    app.kubernetes.io/managed-by: argocd
    argocd.argoproj.io/project: aipaas
spec:
  project: aipaas
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  source:
    repoURL: https://github.com/lionelmarcus10/aipaas.git
    path: apps/pod-security
    targetRevision: master
    directory:
      exclude: application.yaml
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
    retry:
      limit: 5
      backoff:
        duration: 30s
        maxDuration: 2m
        factor: 2
